### ISSUE TITLE
Doesn't seem to work right on Paper 1.16

### ISSUE THREAD

**Issue by IITFA** [alex55132/EnchantmentsExtractor#1]
So, just installed it and went through the motions of testing. I grabbed a diamond sword and put two enchantments on it. Did the disenchant command and got two books. Those books seemed like enchantment books but there was no lore or name or anything saying what it was. Trying to enchant the sword using one of the books failed. No errors in the console. The current Paper build being used is 117.

**Comment by alex55132** [comment]
Um, that's really really weird, can you please tell me which economy plugin are you using (if using one) and the config.yml from the plugin? Also, have you installed the Vault plugin?

@IITFA

**Comment by IITFA** [comment]
Sorry, I don't usually check my github very often. I was using EssentialsX but have switched to Phantom Economy and just now switched to "The New Economy" (https://www.spigotmc.org/resources/the-new-economy.7805/). Just redownloaded and tested again, same result. I don't think it has anything to do with the economy plugin since the same result happened on three different ones. Yes, I have vault installed.

The config is untouched: https://pastebin.com/raw/zMjRfbc0

Paper Spigot version is now Paper version git-Paper-136 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by alex55132** [comment]
Can you please add the server logs when initializing the server? Check if there's any error there regarding the plugin initialization? Maybe when entering the command?

@IITFA

**Comment by IITFA** [comment]
This is everything in the console log about the plugin:
https://pastebin.com/raw/nHsJuYr6

When I do /disenchant there are no errors or any messages in the console log. The test: diamond sword with sharpness. Run command. Sword stops being enchanted, I get a book, but there is nothing in the book and the book is useless.

![2020-08-26_22 17 03](https://user-images.githubusercontent.com/28982837/91376027-25288f00-e7ea-11ea-91d5-34479dd2858b.png)
![2020-08-26_22 17 12](https://user-images.githubusercontent.com/28982837/91376032-28bc1600-e7ea-11ea-9c35-ec65fb82ff96.png)
![2020-08-26_22 19 38](https://user-images.githubusercontent.com/28982837/91376100-57d28780-e7ea-11ea-8905-3cc0a339c47d.png)

**Comment by alex55132** [comment]
In the screenshot of the server it appears that you enchant that sword with level 6 of Sharpness. As I know, the maximum level of Sharpness available in minecraft books is 5. Can you please try it again with a Sharpness V enchanted sword and tell me if the error persists?

@IITFA

**Comment by IITFA** [comment]
Yep, it looks like the non-vanilla enchantments don't disenchant. I have the following enchantment plugin installed if it helps..

https://www.spigotmc.org/resources/enchantment-solution.59556/

Sharpness 5 disenchants properly. Height++ (on pick) doesn't and neither does sharpness 6 on sword.

**Comment by alex55132** [comment]
The plugin is not intended to work with non-vanilla echantments, if you want to have it added, feel free to open a new issue so I can add it to the TODO list or a pull request if you prefer developing yourself. 

Closing.
