### ISSUE TITLE
Request: Support Enchantment Solution

### ISSUE THREAD

**Issue by IITFA** [alex55132/EnchantmentsExtractor#2]
As per your reply, I am opening a request.

Enchantment Solution:
https://www.spigotmc.org/resources/enchantment-solution.59556/

Why should Enchantments Extractor support enchantments from Enchantment Solution? Enchantment Solution is probably the best open source enchantment plugin for Spigot. It includes a lot of neat enchantments that are not OP (mostly, but the OP ones can easily be disabled) and fits well with the game.

**Comment by alex55132** [comment]
@IITFA [1.3](https://github.com/alex55132/EnchantmentsExtractor/releases) has been released. ES is supported now.

Closing.
