### ISSUE TITLE
[Feature] Add a "failsafe" when trying to extract non-vanilla enchants

### ISSUE THREAD

**Issue by joex92** [alex55132/EnchantmentsExtractor#4]
**Main idea**
When trying to extract enchants from an item that has non-vanilla enchants, It doesn't try to extract the non-vanilla enchants.

**Description**
- If an item has only non-vanilla enchants, show a message saying something like "no valid enchants found". 
- If the item has both, vanilla and non-vanilla enchants, ONLY extract the vanilla ones, leaving the non-vanilla enchants intact, and, if possible, add an extra configurable cost, that way players would think twice before doing it.

**Comment by alex55132** [comment]
@joex92 Implemented in version [1.4](https://github.com/alex55132/EnchantmentsExtractor/releases/tag/1.4), now available for download in releases tab.

Closing.

**Comment by joex92** [comment]
wow thanks! that was faster than expected... 👍
