### ISSUE TITLE
Lapis_Lazuli not working as payment material

### ISSUE THREAD

**Issue by Nericu** [alex55132/EnchantmentsExtractor#7]
Trying to set Lapis_Lazuli as the material payment and it still defaults back to trying to use diamonds.

I have tried different varients of the lapis.
- Lapis
- LapisLazuli
- Lapis Lazuli
- Lapis_Lazuli
and none of them work.

I originally thought it was maybe an issue with the plugin not working with material that have a "_" in their name but tried stone_buttons and they worked just fine. So, seems to be an issue with just Lapis_Lazuli. You also get no errors in the console as it just defaults to using diamonds. 

This is everything from the console regarding this plugin:
[14:30:34] [Server thread/INFO]: [EnchantmentsExtractor] Enabling EnchantmentsExtractor v1.4*
[14:30:34] [Server thread/INFO]: [EnchantmentsExtractor] Intializing EnchantmentsExtractor...
[14:30:34] [Server thread/WARN]: [EnchantmentsExtractor] eng

This is my config:
#If true the plugin uses the Vault integration if installed
economyEnabled: false
#Price that a disenchant cost with the Vault integration
disenchantPrice: 15
#If the Vault integration is disabled, use this material as payment. Note: If bad format or material not found, the plugin uses the default (DIAMOND)
materialPayment: LAPIS_LAZULI
#Custom price for material-based payments. If its < 0 the plugin will use the default values (1 for enchantment level + 1)
materialCustomPrice:
  basePrice: 1
  #Per level price enchantment
  perLevelPrice: 1
messages:
  #Selected language
  language: eng
  eng:
    EnchantmentExtractionSuccess: Enchantments extracted!
    NoEnchantmentExtracted: No enchantments were extracted. Check if you have enough material/money for it!
    SomeEnchantmentExtracted: Some enchantments were not extracted! Do you have enough material/money?
    NoEnchantmentInItem: The current item doesn't have any enchantment!
    NoPermissionMessage: You dont have permissions to use this command!
    ConsoleError: This is not a console command!
    UpdateAvailableMessage: There is a new update available.
    NoUpdateAvailableMessage: There is not a new update available.
    InvalidEnchantmentLevel: Invalid enchantment level (Are you disenchanting vanilla enchantments?)
  esp:
    EnchantmentExtractionSuccess: Encantamientos extraidos!
    NoEnchantmentExtracted: No se han podido extraer todos los encantamientos. Tienes suficientes materiales/dinero para ello?
    SomeEnchantmentExtracted: No se han podido extraer algunos encantamientos. Tienes suficientes materiales/dinero para ello?
    NoEnchantmentInItem: Este objeto no tiene ningun encantamiento!
    NoPermissionMessage: No tienes permiso para usar este comando!
    ConsoleError: No es un comando de consola!
    UpdateAvailableMessage: Hay una actualizacion disponible
    NoUpdateAvailableMessage: No hay actualizaciones disponibles
    InvalidEnchantmentLevel: Nivel de encantamiento invalido. ¿Estás desencantando encantamientos vanilla?

**Comment by alex55132** [comment]
Hello @Nericu, try `lapis_lazuli`, it is the item identifier ingame as stated [here](https://minecraft.fandom.com/wiki/Lapis_Lazuli#Data_values)

**Comment by Nericu** [comment]
I did indeed try lapis_lazuli as the identifier and it still fails to work.

**Comment by alex55132** [comment]
Okay, I will need to know which Minecraft version are you using and which server are you using (Spigot, Paper...)
I will have a look to see what is happening @Nericu

**Comment by Nericu** [comment]
Minecraft 1.20.1
The server is running paperMC 1.20.1 #55

**Comment by alex55132** [comment]
I found the issue and updated the plugin in release [v1.5](https://github.com/alex55132/EnchantmentsExtractor/releases/tag/1.5).
Let me know if this finally fix your problem. @Nericu

**Comment by Nericu** [comment]
Awesome thank you so much! I wont be able to test it until tomorrow night so I will let ya know for sure then!

**Comment by Nericu** [comment]
Just checked and can confirm this is working now with lapis. Thank you for taking the time to resolve the issue!
